### ISSUE TITLE
Change order of forthcoming books so that soonest pub date appears first 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#13]
At the moment the most recent entry appears so the September books are appearing up higher than they  the August books. Can we flip it?

**Comment by budparr** [comment]
Agh, I know - I've been struggling with this and have yet to come up with a solution without resorting to some sort of manual ordering. I'll keep trying.

**Comment by ndbooks** [comment]
Cool!

On Thu, Mar 19, 2015 at 12:33 PM, Bud Parr <notifications@github.com> wrote:

> Agh, I know - I've been struggling with this and have yet to come up with
> a solution without resorting to some sort of manual ordering. I'll keep
> trying.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/13#issuecomment-83652624>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
the only thing I've figure out so far, for the new & forthcoming page, is to order them by genre then date, but that gets a bit funky. may have to do some sort of manual ordering on these

**Comment by budparr** [comment]
think I have a fix. standby

**Comment by budparr** [comment]
Q: do you want this on the new & forthcoming page, or on the genre pages as well?

**Comment by ndbooks** [comment]
no the genre pages can stay as they are. If I don't want books so far out to appear I can just hide them. Otherwise gets too confusing. Does that work for you?

**Comment by ndbooks** [comment]
PLEASE NOTE: Pamphlets is still spelt wrong!

**Comment by ndbooks** [comment]
they'll crucify me if there is a phamplet button

**Comment by budparr** [comment]
CRAP!

and yes! running out to a meeting, will push changes as soon as I get back

**Comment by budparr** [comment]
I'm an idiot!

**Comment by ndbooks** [comment]
haha! don't sweat it! But imagine the uproar... ha

**Comment by budparr** [comment]
So you'll see a switch when you go to add a new book that says "Show in Forthcoming." which allows me to segregate those books and sort how I want. You don't really need to do anything, unless you do not want something to show up there, in which case, you can switch it off, but otherwise there'll be no action on your part (even after the book is no longer forthcoming).

**Comment by budparr** [comment]
it will take a few minutes for all the books to show up, by the way

**Comment by budparr** [comment]
If you like, I can put, say, two forthcoming books at the front of the list (just before the just published) and the rest after the list as they are now.

**Comment by ndbooks** [comment]
I can't see this issue on github anymore so I hope you get this email:

I think it's great how you have it, but perhaps we should have
- three rows of new
- two rows of forthcoming
- three rows of bestsellers

what do you think?

On Thu, Mar 19, 2015 at 3:52 PM, Bud Parr <notifications@github.com> wrote:

> If you like, I can put, say, two forthcoming books at the front of the
> list (just before the just published) and the rest after the list as they
> are now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/13#issuecomment-83737934>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Sometimes I'll close an issue when I make the fix. On the github site, you can click the "closed" button to see events that are already closed.




I can control the number of books (so not rows, exactly), but, I think you don't need to control it too terribly closely. I just think it's good to have the next couple of upcoming books, then some new stuff. Probably dictated by what someone in the industry would want to see because this page is really for them, for the most part.




The bestsellers are entirely dictated by you. Go to the "--Global--" section and look for the bestsellers group.


—
