### ISSUE TITLE
Please make top nav more visible

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#20]
Dear Bud,

I have looked at the site on two different (rather crappy) monitors now and the top nav doesn't look so hot. The lines look a bit broken up on the logo and it's not terribly easy to read. Can we brighten up the text a bit? It might even need to be a bit bigger. I'm sure this is an infuriating suggestion, but I thought I would let you know that its a different experience on a shitty screen, which we can assume a lot of people in publishing and bookstores at least are using...

**Comment by budparr** [comment]
can you send me screenshots, please?

**Comment by ndbooks** [comment]
[image: Inline image 1]

that's from mine (above) and below is from my girlfriend's work computer

[image: Inline image 1]



On Fri, Mar 20, 2015 at 2:55 PM, Bud Parr <notifications@github.com> wrote:

> can you send me screenshots, please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/20#issuecomment-84099788>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
I'm not getting the images

**Comment by budparr** [comment]
if you're dropping them into an email, you should probably go right to github and drop them here, or email me the images directly

**Comment by ndbooks** [comment]
![screen shot 2015-03-20 at 3 03 37 pm](https://cloud.githubusercontent.com/assets/10980123/6759122/15248432-cf14-11e4-900a-c6a2d06ed97b.png)

**Comment by ndbooks** [comment]
![screen shot 2015-03-20 at 2 56 02 pm](https://cloud.githubusercontent.com/assets/10980123/6759126/1a33f9f8-cf14-11e4-9141-29315c912d23.png)

**Comment by budparr** [comment]
So, in your comment, I'm not sure where you're talking about text and where you're talking about the logo, so try to treat them separately. 

**Text**
Changing the size, I think would be a mistake. As well as changing the color, at least against the black. I can lighten a bit, but bad monitors are bad monitors and it's a delicate typeface. I obviously wouldn't suggest changing the actual typeface because this is your brand font. It's not a great font (at least on the web; it was designed specifically for a magazine, for Martha Stewart, which seems funny to me, in an ironic way). And, to give it credit, it is a lively companion to Raleway, which is only good for body copy,  and Verlag, which is only good for headings.

How does the history page (essentially the inverse of this) look? The color and size are, you know, a balance with everything else on the page (aside: I note that we often both think the other is going to hate us; so far so good, but don't hate me on this, because everything here is the result of lots and lots of trial and error and trying stuff - so don't think because I say what sounds flippant, "it won't work" is, even if subject to being wrong, is not without though. end aside). 

I can change the weight of the font. It's currently a 500 weight font (which is not that light!) and I can make it 600, but it'd have to be 600 everywhere it's used (the only other place is on the quotes) because these fonts are heavy (font size) and we can't add to the weight. That "might" help and it's easy enough to try if you don't mind having a look when it's set. 

That's really the only thing that I can think of. When asked to balance the needs of older bad computers with the demands of newer, more capable computers, we're typically going to choose the latter because the users of the former will assume it's them and the users of the latter will assume it's you. 

**Logo**
I'm at a loss as to what to suggest here. It's a complex graphic and I'm not a graphic designer and don't really know how I would possibly change it. To make it larger - see the 'balance' comment above. To change it much at all would require a complete rethink of the nav.


_another aside: wouldn't you have liked to get a simple, one line response!_

**Comment by ndbooks** [comment]
hmm okay. I'm confused. But I looked at the history page and the other lighter pages and it doesn't seem to be a problem. It's the black that is making it hard to see.

**Comment by budparr** [comment]
I can try lightening it a bit then. Guess I could have saved myself the academic article length post!

**Comment by budparr** [comment]
By the way - I created a label, which you should see on the right of the issues), called "blocking" please label anything that will block launching the site with that so we know what our priorities are.

I'm going to try to get as much as I can get done next week, but FYI, I'm leaving on April 2nd until mid-month on vacation.

**Comment by budparr** [comment]
I just made the the font weight 600 and lightening the logo a bit. It looks "better," which by better more legible, if, I have to say, less elegant on my retina screen. I'll have it up live in a bit for you, if you're around.
