### ISSUE TITLE
Author photo image credit needed

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#23]
Dear Bud, 
Am I missing a field or is there no option for crediting author photos?

**Comment by ndbooks** [comment]
in particular really need to credit Cesar Aira's pic to Nina Subin or everyone will throttle me..

**Comment by budparr** [comment]
Been meaning to do that. give me just a few minutes. (I see you've mastered labels!)

**Comment by ndbooks** [comment]
ha ha

On Tue, Mar 24, 2015 at 4:09 PM, Bud Parr <notifications@github.com> wrote:

> Been meaning to do that. give me just a few minutes. (I see you've
> mastered labels!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/23#issuecomment-85673320>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
I added the field. I left it completely open, that is, if you want it to say "photo credit" "credit" whatever, you'll need to put it in. I made it that way so that you could also use it to credit the banner photo and label as such. I put it right under the author photo, but will evaluate that once I see some of them up.

**Comment by budparr** [comment]
it'll show up on the site in a bit
