### ISSUE TITLE
Glitch? Some books that were published ions ago are showing up as forthcoming.. 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#31]
For example David Hintons poetry translations which came out in the 90s. It seems to be a problem with books from the 90s or earlier... I can go through and change each one but if there is an easy fix then PRAISE!

**Comment by budparr** [comment]
You mean, specifically, showing "available…" on the book page?

**Comment by ndbooks** [comment]
Most books on the site published in the 90s are showing up as forthcoming... ?

**Comment by budparr** [comment]
can you send me an example? (I like the events page image, btw)

**Comment by ndbooks** [comment]
thanks! I've been changing all the ones I find with forthcoming clicked. but here's bei dao for example: 

http://www.ndbooks.com/author/bei-dao/

**Comment by budparr** [comment]
You're speaking specifically about where it says on some books "Available…" in red, correct? The forthcoming switch wouldn't effect this, as it's only for showing books on the New & Forthcoming page.

It is some sort of bug. I've tried to solve this once before and will look again. It's a bit complicated, but I show that notice by converting the "publication date" field into what's called a Unix Time stamp (which is the number of seconds since Jan 1, 1970) and compare it to the current time, also in Unix format, and if the resulting number is negative, then it shows as forthcoming, again, presuming we're talking about the same thing. So, the dates appear to be right and I don't know if has to do with the dates themselves screwed up or my code, but I think it's the former, I just haven't figured out how.

**Comment by ndbooks** [comment]
Yes. BUT I do think it's the switch because all of them were switched to green for yes. I can go through and do it individually for all high traffic/local/living authors.

**Comment by budparr** [comment]
they're only green for yes, because I set it that way so you wouldn't have to touch it when you add a new book. So, the old ones will be switched on if they're saved again with the switch on, but not as of now, and they still wouldn't do anything to the new and forthcoming page.




At any rate, I'll change the default to off, which I think will be less confusing. Standby.


—

**Comment by budparr** [comment]
I made the field so the default is not to show in forthcoming (tiny bit more work, but definitely less potential for confusing), and I think I fixed the other. Give it a bit to update on the live site and check a few.
