### ISSUE TITLE
Where are the missing blog images? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#34]
Noticing that there's a lot of blog image content that isn't showing up... do I have to upload all new images or is there a way to get them back?

**Comment by budparr** [comment]
Unfortunately, no, because we have a new way of doing images. You can reach the old site here: http://www.ndbooks.com.php54-2.dfw1-1.websitetestlink.com (I'll leave that up for ~30 days, but have to take it down at some point soon) and if you just find an image, right click to get a menu where you can open the image in a new tab and you can just use that URL to load the image anew.

**Comment by ndbooks** [comment]
Great, that works. thanks!

On Fri, Mar 27, 2015 at 5:26 PM, Bud Parr <notifications@github.com> wrote:

> Unfortunately, no, because we have a new way of doing images. You can
> reach the old site here:
> http://www.ndbooks.com.php54-2.dfw1-1.websitetestlink.com (I'll leave
> that up for ~30 days, but have to take it down at some point soon) and if
> you just find an image, right click to get a menu where you can open the
> image in a new tab and you can just use that URL to load the image anew.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/34#issuecomment-87096775>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks
