### ISSUE TITLE
Homepage suggestion 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#9]
Can we please add a small category to each of the content boxes on the homepage? 

For example: 
Event
New 
Review
Forthcoming 
etc.?

**Comment by budparr** [comment]
up for discussion - if I were going to get that literal with it I'd change the presentation altogether as this is meant to be presentational and random, hopefully fun and interesting. All publisher websites, in my view, try too hard to sell and organize when a reader arrives, and fail to delight; whether or not this layout is successful at that, it's hard to say, but that's the aim. 

Having said all that - right now I'm just trying to get it out the door, but the home page is a blank slate that we can change quite a bit, from the content to the layout, and in fact I think we should completely change the layout from time to time or at least find ways to mix things up. That's part of the delight too. Every publisher website has the same little carousel/slideshow and a row of books and a row of news and publishers hope that someone loves them enough to come back and see if the content changes, and I don't think that's enough. 

Anyway - this all might seem harsh writing it out here, but you know where I'm coming from - just trying to do better!

**Comment by ndbooks** [comment]
No problem. I've shown it to a couple of people now and each person commented on the gray squares. Can they all be white and only become gray when you hover over them? The different grays are a little confusing. Or if a highlight is really needed could we use the lightest most subtle shade of gray for every square?

**Comment by ndbooks** [comment]
Hi Bud, 
I understand where you are coming from with not labeling the squares BUT I do think that the events at the top need a header of some kind. What do you think? Could it just say "upcoming events?" What do you think?

**Comment by budparr** [comment]
It was your intern (sorry, I'm bad with names) who made the excellent suggestion that if you put the date before the heading it will be instantly be recognized as an event.

The short of what I'm trying to get at with my ranting and raving is that the homepage is not for information, necessarily (even though there is indeed a lot of information), but to convey in a very visual way that New Directions is a very cool publisher of the most interesting things (I say things because I think of your events as part of your value) to a very cool audience. That's the home page's job. The other pages can be more literal. Make sense? I'll stop ranting!

**Comment by budparr** [comment]
Sorry, I missed over your earlier comment about the shading. I can make those all one shade. I tried it without any shading at all, but felt it went too far. I'm curious (and don't mean to give push back on every single thing!) what was confusing about it? I think the shades just make it more visually interesting, even if subtle - it's a fine line between a cascade of interestingness and, pinterest. :) Did people think that the shades were meant to convey meaning? And, if so, because I used the same shading scheme on the about page (and note that the book pages are uniformly shaded because they're uniformly shaped), do you want them uniform too?
